-- RUN THIS IN YOUR SUPABASE SQL EDITOR
-- ADD START_DATE TO PROJECTS
ALTER TABLE projects ADD COLUMN IF NOT EXISTS start_date date DEFAULT CURRENT_DATE;

-- REFRESH SCHEMA CACHE IN SUPABASE AFTER RUNNING THIS
