-- RUN THIS IN YOUR SUPABASE SQL EDITOR TO FIX TREASURY & ADD NEW FEATURES
-- ADD MISSING COLUMNS TO TRANSACTIONS TABLE

ALTER TABLE transactions ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS client_id uuid REFERENCES clients(id);
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS is_recurring boolean DEFAULT false;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS recurring_interval text; -- 'monthly', 'yearly', 'once'

-- REFRESH SCHEMA CACHE IN SUPABASE AFTER RUNNING THIS
