-- ADD ASSET TRACKING COLUMNS TO PROJECTS
ALTER TABLE projects 
ADD COLUMN IF NOT EXISTS figma_url TEXT DEFAULT '-',
ADD COLUMN IF NOT EXISTS drive_url TEXT DEFAULT '-',
ADD COLUMN IF NOT EXISTS github_url TEXT DEFAULT '-';
